# Generated by Django 5.0.1 on 2024-01-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
