# Generated by Django 5.0.1 on 2024-01-15 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_itemimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True)),
                ('dateJoined', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
