# Generated by Django 5.0.1 on 2024-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_buyer_email_remove_buyer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
