# Generated by Django 5.0.1 on 2024-01-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='howmany',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalcolst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
