# Generated by Django 5.0.1 on 2024-01-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='cartlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
