# Generated by Django 5.0.1 on 2024-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_buyer_cartlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
