# Generated by Django 5.0.1 on 2024-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='cartlist',
        ),
        migrations.AddField(
            model_name='buyer',
            name='cartlist',
            field=models.ManyToManyField(blank=True, to='app.item'),
        ),
    ]
