# Generated by Django 5.0.1 on 2024-01-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_buyer_cartlist_buyer_cartlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='cartlist',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='cart',
            field=models.ManyToManyField(through='app.CartItem', to='app.item'),
        ),
    ]
